### ISSUE TITLE
Feature request - Sync playlist of friends

### ISSUE THREAD

**Issue by sebitr** [Fetcharr/fetcharr#12]
Hi there,

Thank you for this tool—it's fantastic and works exactly as intended!

I have a feature request that I believe would enhance the user experience even further. It would be great to have the ability to sync the watchlist not only of the main account but also the watchlists of all friends associated with that account. This would allow friends to request movies easily.

Thank you for considering this suggestion! I look forward to seeing how the tool evolves.

**Comment by maxnatamo** [comment]
Hello,

Thank you very much for your feedback! I'm happy you like the tool, so far.

Fetching the watchlist of friends was actually in the original "roadmap", but I must've forgotten about it again. I'll make start experimenting on it; see what I can come up with.

**Comment by maxnatamo** [comment]
Support has been added in v0.1.4, so you should be able to pull it from the container registry now.

**Comment by sebitr** [comment]
Thanks a lot. It works perfectly.
